### ISSUE TITLE
Create requirements for create post

### ISSUE THREAD

**Issue by romanl231** [roman266/project_garage#11]
### Requirements

1.Title (Logo)
2.Left side box

   1. Profile picture with nickname
   2. button "My profile"
       when pressed moves user to my profile page
   3. button "Friends"
       when pressed moves user to my friend page
   4. button "Messages"
       when pressed moves user to my messages page
   5. button "My posts"
       when pressed moves user to my my posts page
   6. button "Post"
       when pressed moves user to my create post page

3.Search bar
   - search bar in the header area
     placeholder: "Search"

4.Make a post

1. Media Upload
   - Users should be able to upload an image or video file.
   - Allow drag-and-drop functionality for media files.
   - Button "Select on computer"
     when pressed select a file from the computer

2. Post Text Area
   - Include a text input area where users can add captions or descriptions
     placeholder: "add some description"
  
3. Submit Button
   - Button "Post" 
     when pressed submit the post
   - Disable the "Post" button until media is uploaded.

4. Cancel Option
   - Button "Cancel" 
     when pressed clears all input fields
   
### Acceptence criteria

1. Media Upload
   - Only specific file types (JPEG, PNG, MP4).
   - Limit the file size to a maximum (5MB - photo, 50MB - video).

2. Post Text Area
   - Limit the text length to a predefined character limit (500 characters).

3. Submit Button
   - Doesn't work when user hasn't added media and/or a caption.

4. Succsessful post:
   - If all fields are validated, the user create post.

**Comment by vvas1** [comment]
tory should be only only about functionality related to create post. Header, footer and left nav bar are part of global layout and are not related to this story.
