### ISSUE TITLE
Create requirements for my profile

### ISSUE THREAD

**Issue by romanl231** [roman266/project_garage#7]
### Requirements

1.Title ( My profile ):
2.Profile information

1. Profile picture with nickname
2. button "My profile"
when pressed moves user to my profile page
3. button "Friends"
when pressed moves user to my friend page
4. button "Messages"
when pressed moves user to my messages page
5. button "My posts"
when pressed moves user to my my posts page
6. button "Post"
when pressed moves user to my create post page

3.Search bar

1. search bar in the header area 

      - placeholder: "Search"

4.Profile editing

1. curent profile information, including:

      - username
      - email
      - password( hide )
2. possibility to change profile information
3. buton "Edit" 
when pressed change profile information

### Acceptence criteria

1. email validation
   - user gets error if email doesn't pass validation: "Incorrect email format"
2. password validation
   - user gets error if password doesn't pass validation: "Minimal lenght of password must be 8 characters"
3. succsessful change:
   - if all fields are validated, the user changes an account information

**Comment by vvas1** [comment]
search bar is out of this story
