### ISSUE TITLE
Create requirements for friends

### ISSUE THREAD

**Issue by romanl231** [roman266/project_garage#8]

**Comment by DeepDF** [comment]
Requirements
1.Title (Logo)
2.Left side box

  1. Profile picture with nickname
  2. button "My profile"
     when pressed, moves user to my profile page
  3. button "Friends"
     when pressed, moves user to my friend page
  4. button "Messages"
     when pressed, moves user to my messages page
  5. button "My posts"
     when pressed, moves user to my my posts page
  6. button "Post"
     when pressed, moves user to my create post page

3.Friends feed(list)
  1.  Profile picture with nickname
  2.  button "Message"
       when pressed, moves user to private message with this user

4.Friends requests(list)
  1.  Profile picture with nickname
  2.  Description "Sent a friend request"
  3.  button "Accept"       
       when pressed, adds the user to your friends and removes request
  4.  button "Reject"       
       when pressed, removes request

**Comment by DeepDF** [comment]
user can remove(and block) friends
