### ISSUE TITLE
Create requirements for message

### ISSUE THREAD

**Issue by romanl231** [roman266/project_garage#9]
### Requirements
1.Title (Logo)
2.Left side box

- Profile picture with nickname
- button "My profile"
 when pressed, moves user to my profile page
- button "Friends"
   when pressed, moves user to my friend page
- button "Messages"
   when pressed, moves user to my messages page
- button "My posts"
   when pressed, moves user to my my posts page
- button "Post"
   when pressed, moves user to my create post page

3. Search bar
  - search bar in the header area
  - placeholder: "Search"

4. Avaible chats field
  - list contains all your chats, contains profile picture and nickname of your chatmate
5. Chat field
   - header contains profile picture and nickname of your chatmate
   - your chatmate messages located at the left side of the field
   - your messages located at the right field of the field
   - placeholder(Type message here)
   - add file button
     if pressed open your desktop folder

### Acceptation criteria
1.  message validation
     you can send only <= 10000 characters message
     if exceed the limit you get a warning: "Message maximal lenght the maximum message length is 10,000 characters" 
2. file validation
    you can send only <= 5 MB file message
    if exceed the limit you get a warning:"File maximal size is 5 MB"

**Comment by vvas1** [comment]
Story should be only only about functionality related to messages. Header, footer and left nav bar are part of global layout and are not related to this story. Instead of describing all left nav bar should be said that `button "Messages"
when pressed, moves user to my messages page`
